[supervisord]
nodaemon=true
user=root

[program:xvfb]
command=/usr/bin/Xvfb :1 -screen 0 1280x800x16
autorestart=true
priority=1

[program:fluxbox]
command=/usr/bin/fluxbox
environment=DISPLAY=":1"
autorestart=true
priority=2
startsecs=2

[program:torbrowser]
command=/bin/bash -c "sleep 3 && /opt/tor-browser/Browser/start-tor-browser --verbose --allow-root"
environment=DISPLAY=":1",HOME="/root"
autorestart=true
priority=3
startsecs=5

[program:x11vnc]
command=x11vnc -display :1 -forever -shared -rfbport 5900 -passwd %(ENV_VNC_PASSWORD)s
autorestart=true
priority=4
startsecs=2
